#!/usr/bin/env ruby

require "json"
require_relative "lead"

Lead.load_leads_from_file("leads.json")

Lead.all_sorted_by_date_desc.each do |lead|
  Lead.store_lead_if_valid(lead)
end

Lead.update_change_log
Lead.create_valid_leads_file
Lead.output_summary_to_cli
Lead.output_change_log_file_info
